apiVersion: v2
name: testnet-manager
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
dependencies:
- name: testnet-manager
  version: "1.3.1"
  repository: "https://paritytech.github.io/helm-charts/"
