apiVersion: v2
name: node
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
- name: node
  version: "5.4.0"
  repository: "https://paritytech.github.io/helm-charts/"
